FROM rust:latest AS builder
WORKDIR /app
COPY . .
RUN cargo build --release --bin mock-psp

FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y libssl3 ca-certificates && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY --from=builder /app/target/release/mock-psp /app/mock-psp
CMD ["/app/mock-psp"]
